In [16]:
import efficientfrontier
import bokeh.io
import holoviews as hv
import numpy as np
efficientfrontier.__version__

'0.0.7'

The stocks that we are going to look up.

In [3]:
stocks = ['GOOGL', 'AAPL', 'PG', 'JPM']

For the sake of example, we will get some data for the stocks. For the stocks, we will get the open, close, high, low, and adjusted closing prices on a monthly (the default) timeframe.

In [8]:
stock_data_df = efficientfrontier.get_data(stocks, ['open', 'close', 'high', 'low', 'adjclose'])
stock_data_df.head()

Stock           GOOGL                                                   AAPL  \
Attribute        open      close        high        low   adjclose      open   
date                                                                           
2004-08-01  50.050049  51.236237   56.796795  48.028027  51.236237  2.227143   
2004-09-01  51.401402  64.864868   67.577576  49.519520  64.864868  2.450000   
2004-10-01  65.465462  95.415413  100.075073  64.514511  95.415413  2.794286   
2004-11-01  96.871872  91.081078  100.900902  80.735733  91.081078  3.750000   
2004-12-01  91.066063  96.491493  100.040039  84.319321  96.491493  4.842143   

Stock                                                      PG             \
Attribute      close      high       low  adjclose       open      close   
date                                                                       
2004-08-01  2.463571  2.512857  2.121428  2.138481  52.759998  55.970001   
2004-09-01  2.767857  2.805000  2.442143  2.402613  55.970001  54.119999   
2004-10-01  3.742857  3.800000  2.689286  3.248953  54.349998  51.180000   
2004-11-01  4.789286  4.969285  3.717143  4.157295  51.250000  53.480000   
2004-12-01  4.600000  4.853571  4.400000  3.992987  53.560001  55.080002   

Stock                                              JPM                        \
Attribute        high        low   adjclose       open      close       high   
date                                                                           
2004-08-01  56.090000  52.610001  35.994305  37.230000  39.580002  39.799999   
2004-09-01  56.950001  53.270000  34.804573  39.520000  39.730000  40.250000   
2004-10-01  54.900002  50.529999  32.913860  39.900002  38.599998  40.450001   
2004-11-01  54.950001  50.790001  34.555981  38.770000  37.650002  39.910000   
2004-12-01  57.400002  53.549999  35.589828  37.799999  39.009998  39.480000   

Stock                             
Attribute         low   adjclose  
date                              
2004-08-01  35.900002  26.139782  
2004-09-01  38.950001  26.238848  
2004-10-01  36.320000  25.492565  
2004-11-01  37.060001  25.076508  
2004-12-01  37.250000  25.982332

Now, we show how to get the returns for our stocks, on the default monthly basis.

In [10]:
returns_df = efficientfrontier.get_returns(stocks)
returns_df.head()

GOOGL      AAPL        PG       JPM
date                                              
2004-09-01  0.265996  0.123514 -0.033053  0.003790
2004-10-01  0.470988  0.352258 -0.054324 -0.028442
2004-11-01 -0.045426  0.279580  0.049891 -0.016321
2004-12-01  0.059402 -0.039523  0.029918  0.036122
2005-01-01  0.014679  0.194100 -0.033588 -0.043066

Now, we will get the mean vector and covariance variance for the stocks.

In [17]:
means, variances = efficientfrontier.get_mean_and_variance(stocks)
print('The means are:', np.transpose(means))
print('The covariance matrix is:\n', variances)

The means are: [[0.0220073  0.03178681 0.00761934 0.01178513]]
The covariance matrix is:
 [[0.00795364 0.00411011 0.00028418 0.00168817]
 [0.00411011 0.00912217 0.00078359 0.00133717]
 [0.00028418 0.00078359 0.00178646 0.00082579]
 [0.00168817 0.00133717 0.00082579 0.00570995]]


Here, we get the Sharpe Weights for each of the stocks and display the DataFrame.

In [18]:
df = efficientfrontier.get_sharpe_weights(stocks)
print(df)

   stock    weight
0  GOOGL  0.162968
1   AAPL  0.370312
2     PG  0.363991
3    JPM  0.102729


Now, we get the plot the efficient frontier graph for our stocks.

In [19]:
graph = efficientfrontier.efficient_frontier_graph(stocks, width=600, height=500, use_sharpe_portfolio=True)
p = hv.render(graph)
p.legend.location='bottom_right'
bokeh.io.show(p)

<br/>